"""Curated skill dictionary: canonical display name -> surface forms to search for.

Used by the local keyword-matching engine (no external API calls). Keep entries
lowercase in the alias lists; the canonical key is the display-friendly form.
"""

SKILLS: dict[str, list[str]] = {
    # Languages
    "Python": ["python"],
    "Java": ["java"],
    "JavaScript": ["javascript", "js"],
    "TypeScript": ["typescript", "ts"],
    "C": ["c programming"],
    "C++": ["c++"],
    "C#": ["c#"],
    "Go": ["golang", "go lang"],
    "Rust": ["rust"],
    "Kotlin": ["kotlin"],
    "Swift": ["swift"],
    "PHP": ["php"],
    "Ruby": ["ruby"],
    "Scala": ["scala"],
    "R": ["r programming", "r language"],
    "MATLAB": ["matlab"],
    "Perl": ["perl"],
    "Dart": ["dart"],
    "SQL": ["sql"],
    "HTML": ["html", "html5"],
    "CSS": ["css", "css3"],
    "Bash": ["bash", "shell scripting", "shell script"],

    # Frontend
    "React": ["react", "react.js", "reactjs"],
    "Angular": ["angular", "angular.js", "angularjs"],
    "Vue": ["vue", "vue.js", "vuejs"],
    "Next.js": ["next.js", "nextjs"],
    "Svelte": ["svelte"],
    "Redux": ["redux"],
    "Tailwind CSS": ["tailwind", "tailwind css"],
    "Bootstrap": ["bootstrap"],
    "jQuery": ["jquery"],
    "Webpack": ["webpack"],
    "Vite": ["vite"],
    "Sass": ["sass", "scss"],

    # Backend
    "Node.js": ["node.js", "nodejs", "node js"],
    "Express.js": ["express.js", "expressjs", "express"],
    "Django": ["django"],
    "Flask": ["flask"],
    "FastAPI": ["fastapi"],
    "Spring Boot": ["spring boot", "springboot"],
    "Spring": ["spring framework"],
    "Hibernate": ["hibernate"],
    "Laravel": ["laravel"],
    "Ruby on Rails": ["ruby on rails", "rails"],
    "ASP.NET": ["asp.net", "asp.net core"],
    ".NET": [".net", "dotnet", ".net core"],
    "GraphQL": ["graphql"],
    "REST API": ["rest api", "restful api", "rest apis"],
    "gRPC": ["grpc"],
    "Microservices": ["microservices", "microservice architecture"],

    # Databases
    "MySQL": ["mysql"],
    "PostgreSQL": ["postgresql", "postgres"],
    "MongoDB": ["mongodb", "mongo"],
    "SQLite": ["sqlite"],
    "Redis": ["redis"],
    "Oracle DB": ["oracle db", "oracle database"],
    "Cassandra": ["cassandra"],
    "DynamoDB": ["dynamodb"],
    "Firebase": ["firebase"],
    "Elasticsearch": ["elasticsearch"],
    "MariaDB": ["mariadb"],

    # Cloud / DevOps
    "AWS": ["aws", "amazon web services"],
    "Azure": ["azure", "microsoft azure"],
    "GCP": ["gcp", "google cloud", "google cloud platform"],
    "Docker": ["docker"],
    "Kubernetes": ["kubernetes", "k8s"],
    "Terraform": ["terraform"],
    "Ansible": ["ansible"],
    "Jenkins": ["jenkins"],
    "CI/CD": ["ci/cd", "ci cd", "continuous integration", "continuous deployment"],
    "GitHub Actions": ["github actions"],
    "GitLab CI": ["gitlab ci"],
    "Nginx": ["nginx"],
    "Linux": ["linux"],
    "Git": ["git"],
    "GitHub": ["github"],
    "Bitbucket": ["bitbucket"],
    "CloudFormation": ["cloudformation"],
    "Serverless": ["serverless"],

    # Data / ML
    "Machine Learning": ["machine learning", "ml"],
    "Deep Learning": ["deep learning"],
    "TensorFlow": ["tensorflow"],
    "PyTorch": ["pytorch"],
    "Scikit-learn": ["scikit-learn", "sklearn"],
    "Pandas": ["pandas"],
    "NumPy": ["numpy"],
    "Data Analysis": ["data analysis"],
    "Data Visualization": ["data visualization"],
    "NLP": ["nlp", "natural language processing"],
    "Computer Vision": ["computer vision"],
    "OpenCV": ["opencv"],
    "Keras": ["keras"],
    "Tableau": ["tableau"],
    "Power BI": ["power bi"],
    "Apache Spark": ["spark", "apache spark"],
    "Hadoop": ["hadoop"],
    "ETL": ["etl"],
    "Airflow": ["airflow"],

    # Testing
    "JUnit": ["junit"],
    "Pytest": ["pytest"],
    "Selenium": ["selenium"],
    "Jest": ["jest"],
    "Mocha": ["mocha"],
    "Cypress": ["cypress"],
    "Unit Testing": ["unit testing", "unit tests"],
    "Integration Testing": ["integration testing"],
    "TDD": ["tdd", "test-driven development"],
    "Postman": ["postman"],

    # Mobile
    "Android": ["android"],
    "iOS": ["ios"],
    "React Native": ["react native"],
    "Flutter": ["flutter"],
    "SwiftUI": ["swiftui"],

    # Tools / other technical
    "Jira": ["jira"],
    "Confluence": ["confluence"],
    "Agile": ["agile", "agile methodology"],
    "Scrum": ["scrum"],
    "Kanban": ["kanban"],
    "Figma": ["figma"],
    "Adobe XD": ["adobe xd"],
    "UX Design": ["ux design", "user experience design"],
    "UI Design": ["ui design", "user interface design"],
    "API Design": ["api design"],
    "OOP": ["oop", "object-oriented programming", "object oriented programming"],
    "Data Structures": ["data structures"],
    "Algorithms": ["algorithms"],
    "System Design": ["system design"],
    "MLOps": ["mlops"],
    "Blockchain": ["blockchain"],
    "Solidity": ["solidity"],
    "Web3": ["web3"],
    "Cybersecurity": ["cybersecurity", "cyber security"],
    "Penetration Testing": ["penetration testing", "pen testing"],
    "Networking": ["networking"],
    "TCP/IP": ["tcp/ip"],
    "Excel": ["excel", "microsoft excel"],
    "PDFBox": ["pdfbox"],

    # Soft skills
    "Communication": ["communication skills", "communication"],
    "Leadership": ["leadership"],
    "Teamwork": ["teamwork", "team player"],
    "Problem Solving": ["problem solving", "problem-solving"],
    "Time Management": ["time management"],
    "Project Management": ["project management"],
    "Critical Thinking": ["critical thinking"],
    "Collaboration": ["collaboration"],
    "Mentoring": ["mentoring", "mentorship"],
    "Presentation Skills": ["presentation skills"],
}

GENERIC_STOPWORDS: set[str] = {
    "the", "and", "for", "are", "but", "not", "you", "your", "with", "have",
    "has", "our", "will", "can", "this", "that", "from", "who", "were", "was",
    "they", "their", "them", "any", "all", "one", "two", "three", "into",
    "out", "over", "under", "such", "than", "then", "when", "where", "what",
    "why", "how", "which", "while", "about", "above", "after", "again",
    "against", "between", "both", "each", "few", "further", "here", "there",
    "these", "those", "very", "just", "should", "would", "could", "must",
    "may", "might", "shall", "also", "per", "via", "etc", "eg", "ie",
}

JD_BOILERPLATE: set[str] = {
    "experience", "years", "team", "work", "role", "responsibilities",
    "candidate", "candidates", "company", "required", "requirements",
    "strong", "knowledge", "skills", "ability", "working", "join",
    "looking", "excellent", "preferred", "plus", "including", "using",
    "help", "build", "building", "develop", "developing", "development",
    "new", "opportunity", "position", "job", "description", "apply",
    "responsible", "across", "within", "well", "good",
    "level", "high", "related", "environment", "based",
    "us", "we", "our", "you", "an", "a", "to", "of", "in", "on", "or",
    "is", "be", "as", "at", "by", "it", "if",
}
